### ISSUE TITLE
Language REQUEST: DE

### ISSUE THREAD

**Issue by heisee** [QuBiT/cucumber-netbeans-plugin#10]
I'd appreciate support for German language as descript in the official languages.yml file.

There's a textmate bundly for feature syntax colouring. I've never tried it out, but I think this bundle simply parses the languages.yml, so it's not necessary to build in support languages explicitly. Maybe this thought can help you for your multi language support?

thanks, heisee

**Comment by QuBiT** [comment]
Hi,

as my own language is German, I'll do you and me the favour.

Since now (Version 1.2.8) this module supports English, French and German all in one. Read the wiki for more informations about it.

It is not so easy to add all languages, because you have to change the lexer rules which are used by the parser. these lexer rules can not be created out of variables, so you have to write patterns (as strings) which match the keywords. if it would be possible to use at this place a variable, i could change the variable according to some preference settings and enable all languages.

cheers

**Comment by heisee** [comment]
Oh wow, that's really cool. 
I tried it out and it works :-)

thanks, heisee
