### ISSUE TITLE
"Save as" action not enabled for .feature files (nb6.7)

### ISSUE THREAD

**Issue by hedgehog** [QuBiT/cucumber-netbeans-plugin#9]
Perhaps this is an error in my configuration, but out-of-the-box, the File>Save As... action is not active for '*.feature' files

**Comment by QuBiT** [comment]
hi,

thanks for the info.

this is not an error of your configuration, also in my installation this is not active.

I'll try to solve this and inform you when it is done.

Cheers

**Comment by QuBiT** [comment]
hi again,

I tried to find a easy solution, but it seems to be a netbeans specific problem.
I tried the same with a .haml file (other module) and also there it is not active.

A quick and dirty way around the problem is to "copy" a file and "paste" it in the same folder and "rename" it from your_1.feature to your designated filename.

If you know another module, which is doing the same like this module, but for a different language and have a working "save as" functionality, then please let me know.
